### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kelset** [react-native-community/upgrade-helper#10]
With this issue I want to line up all the things that we are planning to do in a bullet point manners, so that we can sort of prioritise them and discuss/add/remove new ones.

### Version 1

*This version should be literally the barebone version, so that we can put it in front of the developers and have them start using it & provide feedback.*

- [x] Improve README with useful information
- [x] Add a way to conclude diffs as when they are done (PR at #21) - @lucasbento
- [x] Add useful links section (pointing to a blog post or something like that) (PR at #24)
- [x] Handle binaries (add a way for the user to download them) #22 (PR at #24)

### Version 2

*This one should be the "super powered" version of 1, with more advanced features & cool extras.*

- [x] Add comments on the diff (will be manually created by us, PR at #18) - @lucasbento
- [ ] review the ant design / maybe change it?
- [ ] add the versions in the url (shareability <3) #9

**Comment by pvinis** [comment]
I would move the binaries to v2, but I agree with everything else.

For now we can just get the binaries by doing `init`. Not amazing, but easier than figuring out how to put these somewhere, hosting, linking etc.

**Comment by lucasbento** [comment]
I believe we can force the binaries to be downloaded from GitHub, just need a few mins to investigate that.

**Comment by lucasbento** [comment]
@kelset I added the README improvement to v1, would you be able to work on that?

**Comment by kelset** [comment]
Yeah, I just checked the PRs and I think that once #24 & #18 are merged (optional to have #20 too) we can consider the v1 ready - and I can work on the Readme :3 

I was thinking on using this as inspiration: https://github.com/react-native-community/template/issues/4

**Comment by lucasbento** [comment]
@kelset: awesome!

**Comment by kelset** [comment]
Let's close this in favour of the project :D
